{% set version = load_file_regex(
    load_file="../src/pymars/_version.py",
    regex_pattern='__version__ = "([^"]+)"',
    from_recipe_dir=True
).group(1) %}

package:
  name: pymars
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling

  run:
    - python >=3.10
    - numpy
    - cantera >=3.0
    - networkx
    - h5py
    - pyyaml >=6.0

test:
  imports:
    - pymars

  requires:
    - pytest
    - pytest-cov

  commands:
    - pytest --pyargs pymars

about:
  home: https://github.com/Niemeyer-Research-Group/pyMARS
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python-based chemical kinetic Model Automatic Reduction Software
  description: |
    pyMARS implements multiple methods for automatically reducing the size and
    complexity of detailed chemical kinetic models, including directed relation
    graph (DRG), DRG with error propagation (DRGEP), path flux analysis (PFA),
    and sensitivity analysis (SA).
  doc_url: https://Niemeyer-Research-Group.github.io/pyMARS/
  dev_url: https://github.com/Niemeyer-Research-Group/pyMARS

extra:
  recipe-maintainers:
    - kyleniemeyer
